---
- hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    # - name: move crypto-shell to crypto-shell-old
    #   command: mv /home/ubuntu/crypto-shell /home/ubuntu/crypto-shell-old

    - name: copy and extract application
      ansible.builtin.unarchive:
        src: ../build/crypto-shell.zip
        dest: /home/ubuntu
        owner: ubuntu
        mode: "+x"
        
    - name: copy up secrets
      copy: src=../../crypto-shell-env-prod dest=/home/ubuntu/.env owner=ubuntu
   
    - name: restart app
      service: name=crypto-shell state=restarted