name = "giftcard-app-api"
type = "javascript"

account_id = "8cb6693230e2ff3788e058dfacde43fc"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-20"

\# [[kv_namespaces]]
\# binding = "VIEWS"
\# preview_id = "d96c3b4cf4164af78f326b707568ff31"
\# id = "5c5f567b7fde4418baf641c8ff0d678e"

[build]
command = "make build"

[build.upload]
format = "modules"
main = "./main.mjs"
dir = "./dist"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]

[env.production]
name = "giftcard-app-prod"
