name = "giftcard-app-dev"
type = "javascript"

account_id = "8cb6693230e2ff3788e058dfacde43fc"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-20"

[build]
command = "make build"

[build.upload]
format = "modules"
main = "./main.mjs"
dir = "./dist"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]

[env.production]
name = "giftcard-app-prod"
