name = "giftcard-app-dev"
type = "javascript"

account_id = "09b5ea9e026bcb71bc70ead94aa4efc5"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-20"
webpack_config="webpack.config.js"
kv_namespaces = [
  { binding = "VIEWS", preview_id = "d96c3b4cf4164af78f326b707568ff31", id = "5c5f567b7fde4418baf641c8ff0d678e" }
]

[build]
command = "make build"

[build.upload]
format = "service-worker"


[env.production]
name = "giftcard-app-prod"
webpack_config = "webpack.production.js"